name: Update packages

on:
  # schedule:
  #   - cron:  '0 1 * * *'
  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  update-package:
    strategy:
      fail-fast: false
      matrix:
        package:
          - gdal
          # - geos             # unsupported repo
          - libgeotiff
          # - librttopo        # unsupported repo
          - libspatialindex
          # - libspatialite    # not on GitHub (gaia-gis.it)
          - pdal
          # - postgis          # failing
          - proj
          - python3-fiona
          - python3-geopandas
          - python3-owslib
          - python3-pyproj
          - python3-rasterio
          - python3-shapely
          - grass
          # - qgis            # problem with version tags
          # - qgis-ltr        # problem with version tags

    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.AGITHUB_TOKEN }}

      - name: Update package
        run: >
          nix run github:Mic92/nix-update -- ${{ matrix.package }} --flake

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "pkgs(${{ matrix.package }}): automatic package update"
          body: |
            Update package to the latest upstream version.
            PR auto-generated by [create-pull-request][1].

            [1]: https://github.com/peter-evans/create-pull-request
          branch: ${{ matrix.package }}-update-action-pr
          delete-branch: true
          commit-message: "pkgs(${{ matrix.package }}): update to the latest version"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          assignees: imincik
          # reviewers: imincik
          token: ${{ secrets.FLAKE_AUTOUPDATE_TOKEN }}
